# Generated by Django 6.1.1 on 2026-09-23 10:09

import apps.accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, help_text='Unique creator handle used for your public page URL (e.g. /username/)', max_length=30, unique=True, validators=[apps.accounts.validators.validate_username])),
                ('display_name', models.CharField(help_text='Public creator or brand name', max_length=80)),
                ('bio', models.TextField(blank=True, help_text='Short bio displayed on your profile', max_length=500)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True, help_text='Primary personal or company website')),
                ('public_email', models.EmailField(blank=True, help_text='Public email for inquiries and vCard', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Public phone number for vCard', max_length=30)),
                ('show_contact_form', models.BooleanField(default=True, help_text='Allow visitors to submit their contact info directly from your profile')),
                ('show_save_contact', models.BooleanField(default=True, help_text="Show 'Save My Contact' (.vcf) button on your profile")),
                ('is_public', models.BooleanField(default=True, help_text='Whether your profile is accessible publicly')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('minimal_light', 'Minimal Light'), ('midnight_dark', 'Midnight Dark'), ('sunset_gradient', 'Sunset Gradient'), ('emerald_clean', 'Emerald Clean'), ('neo_brutalism', 'Neo-Brutalism'), ('cyber_sleek', 'Cyber Sleek')], default='midnight_dark', max_length=30)),
                ('bg_type', models.CharField(choices=[('color', 'Solid Color'), ('gradient', 'Gradient'), ('image', 'Background Image')], default='gradient', max_length=20)),
                ('bg_color', models.CharField(default='#0f172a', max_length=25)),
                ('bg_gradient', models.CharField(default='linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%)', max_length=150)),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('text_color', models.CharField(default='#f8fafc', max_length=25)),
                ('button_style', models.CharField(choices=[('solid', 'Solid Fill'), ('outline', 'Outline / Border'), ('soft', 'Soft Tint'), ('glass', 'Glassmorphism')], default='glass', max_length=20)),
                ('button_shape', models.CharField(choices=[('rounded', 'Rounded (12px)'), ('pill', 'Pill (Full Round)'), ('square', 'Square (Sharp)')], default='rounded', max_length=20)),
                ('button_color', models.CharField(default='#3b82f6', max_length=25)),
                ('button_text_color', models.CharField(default='#ffffff', max_length=25)),
                ('font_family', models.CharField(choices=[('inter', 'Inter (Modern Sans)'), ('poppins', 'Poppins (Geometric)'), ('space_grotesk', 'Space Grotesk (Tech Modern)'), ('playfair', 'Playfair Display (Editorial Serif)'), ('jetbrains_mono', 'JetBrains Mono (Developer Mono)')], default='inter', max_length=30)),
                ('avatar_shape', models.CharField(choices=[('circle', 'Circle'), ('rounded', 'Rounded Square'), ('square', 'Sharp Square')], default='circle', max_length=20)),
                ('profile_alignment', models.CharField(choices=[('center', 'Centered'), ('left', 'Left-Aligned')], default='center', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appearance', to='profiles.profile')),
            ],
        ),
    ]
