# Generated by Django 6.1.1 on 2026-09-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='accent_color',
            field=models.CharField(default='#3b82f6', max_length=25),
        ),
        migrations.AddField(
            model_name='appearance',
            name='avatar_border',
            field=models.CharField(choices=[('white', 'White / Light Frame'), ('accent', 'Accent Color Ring'), ('glow', 'Luminous Glow Halo'), ('none', 'No Border')], default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='appearance',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Optional wide profile cover banner', null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='bg_blur',
            field=models.PositiveSmallIntegerField(default=0, help_text='Background blur amount in pixels (0 to 20)'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='bg_overlay_opacity',
            field=models.PositiveSmallIntegerField(default=30, help_text='Darkness overlay (0 to 90%) for background images so text remains readable'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='card_shadow',
            field=models.CharField(choices=[('none', 'No Shadow (Flat)'), ('subtle', 'Subtle Ambient Shadow'), ('elevated', 'Elevated Floating Shadow'), ('glow', 'Color Glow Halo'), ('hard_3d', 'Hard 3D Drop Shadow')], default='subtle', max_length=20),
        ),
        migrations.AddField(
            model_name='appearance',
            name='hover_effect',
            field=models.CharField(choices=[('lift', 'Float Lift (-3px)'), ('scale', 'Gentle Zoom (1.02x)'), ('glow', 'Glow Border Pulse'), ('none', 'Static (No Animation)')], default='lift', max_length=20),
        ),
        migrations.AddField(
            model_name='appearance',
            name='social_position',
            field=models.CharField(choices=[('top', 'Top (Under Bio)'), ('bottom', 'Bottom (Above Footer)')], default='top', max_length=10),
        ),
        migrations.AddField(
            model_name='appearance',
            name='social_style',
            field=models.CharField(choices=[('colored', 'Official Brand Colors'), ('monochrome', 'Monochrome Theme Text'), ('glass', 'Frosted Glass Badges')], default='colored', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='Show verified creator badge'),
        ),
        migrations.AddField(
            model_name='profile',
            name='title_tagline',
            field=models.CharField(blank=True, help_text="Short headline (e.g. 'Founder & Designer' or 'Music Producer')", max_length=100),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='avatar_shape',
            field=models.CharField(choices=[('circle', 'Circle'), ('rounded', 'Rounded Squircle'), ('square', 'Sharp Square')], default='circle', max_length=20),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='bg_gradient',
            field=models.CharField(default='linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%)', max_length=200),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='bg_type',
            field=models.CharField(choices=[('theme', 'Preset Theme Colors'), ('color', 'Solid Color'), ('gradient', 'Custom Gradient'), ('image', 'Custom Background Image')], default='theme', max_length=20),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='button_shape',
            field=models.CharField(choices=[('rounded', 'Smooth Rounded (14px)'), ('pill', 'Full Pill (999px)'), ('square', 'Sharp Square (0px)')], default='rounded', max_length=20),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='button_style',
            field=models.CharField(choices=[('glass', 'Frosted Glassmorphism'), ('solid', 'Solid Vibrant Fill'), ('soft', 'Soft Translucent Tint'), ('outline', 'Minimalist Outline'), ('hard_3d', 'Hard 3D (Brutalist Offset)'), ('glow', 'Ambient Glow Border')], default='glass', max_length=20),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='font_family',
            field=models.CharField(choices=[('inter', 'Inter (Modern Standard)'), ('plus_jakarta_sans', 'Plus Jakarta Sans (SaaS & Tech)'), ('outfit', 'Outfit (Clean Geometric)'), ('dm_sans', 'DM Sans (Friendly Modern)'), ('poppins', 'Poppins (Bold Geometric)'), ('space_grotesk', 'Space Grotesk (Tech Futuristic)'), ('syne', 'Syne (Avant-Garde Creative)'), ('playfair', 'Playfair Display (Luxury Editorial)'), ('jetbrains_mono', 'JetBrains Mono (Developer Clean)')], default='inter', max_length=30),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='profile_alignment',
            field=models.CharField(choices=[('center', 'Centered Profile'), ('left', 'Modern Left-Aligned')], default='center', max_length=20),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='theme',
            field=models.CharField(choices=[('minimal_light', 'Minimalist Snow (Clean White)'), ('midnight_dark', 'Midnight Obsidian (AMOLED Dark)'), ('sunset_gradient', 'Sunset Reverie (Vibrant Rose/Violet)'), ('emerald_clean', 'Matcha & Sage (Organic Forest)'), ('neo_brutalism', 'Neo-Brutalist Pop (Bold Yellow & 3D)'), ('cyber_sleek', 'Neon Cyberpunk (Deep Navy & Cyan Glow)'), ('velvet_cherry', 'Velvet Cherry (Burgundy & Rose Gold)'), ('ocean_aurora', 'Ocean Aurora (Indigo & Teal Wave)'), ('paper_editorial', 'Paper & Ink (Warm Editorial Serif)')], default='midnight_dark', max_length=30),
        ),
    ]
