# Generated by Django 6.1.1 on 2026-09-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_appearance_accent_color_appearance_avatar_border_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Whether the creator has confirmed their email address'),
        ),
    ]
