# Generated by Django 6.1.1 on 2026-09-23 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='links/')),
                ('icon', models.CharField(blank=True, choices=[('', 'No Icon (Default)'), ('globe', 'Globe / Website'), ('video', 'Video / Stream'), ('music', 'Music / Audio'), ('shopping-bag', 'Store / Merchandise'), ('book-open', 'Book / Newsletter'), ('podcast', 'Podcast / Audio'), ('calendar', 'Calendar / Events'), ('sparkles', 'Sparkles / Featured'), ('star', 'Star / Highlight'), ('heart', 'Heart / Support'), ('code', 'Code / Projects'), ('file-text', 'Document / Portfolio')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='profiles.profile')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
