# Generated by Django 6.1.1 on 2026-09-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='currency',
            field=models.CharField(default='GHS', max_length=3),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in Ghana Cedis (GH₵) (0 for free)', max_digits=10),
        ),
    ]
