# Generated by Django 6.1.1 on 2026-09-23 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('twitter', 'X / Twitter'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('threads', 'Threads'), ('spotify', 'Spotify'), ('facebook', 'Facebook'), ('twitch', 'Twitch'), ('discord', 'Discord')], max_length=30)),
                ('url', models.URLField(help_text='Direct link to your social profile', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='profiles.profile')),
            ],
            options={
                'ordering': ['order', 'platform'],
                'unique_together': {('profile', 'platform')},
            },
        ),
    ]
